version: '3'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.6.8
    environment:
      - cluster.name=docker-cluster
      - discovery.type=single-node
    volumes:
      - esdata:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
  zipkin:
    image: openzipkin/zipkin
    environment:
        - STORAGE_TYPE=elasticsearch
        - ES_HOSTS=http://elasticsearch:9200
        - ES_USERNAME=elastic
        - ES_PASSWORD=changeme
    ports:
      - 9411:9411
volumes:
  esdata:
    
