version: '3'

services:
  config:
    image: config
  registration:
    image: registration
    ports:
      - "1111:1111"
  gateway:
    image: gateway
  accounts-server:
    image: accounts-server
    depends_on:
      - "accounts-db"
  accounts-db:
    image: accounts-db
    volumes:
      - accounts-data:/var/lib/mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "1"
  cart-server:
    image: cart-server
    depends_on:
      - "cart-db"
  cart-db:
    image: cart-db
    volumes:
      - cart-data:/var/lib/mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "1"
  categories-server:
    image: categories-server
    depends_on:
      - "categories-db"
  categories-db:
    image: categories-db
    volumes:
      - categories-data:/var/lib/mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "1"
  items-server:
    image: items-server
    depends_on:
      - "items-db"
  items-db:
    image: items-db
    volumes:
      - items-data:/var/lib/mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "1"
  login-server:
    image: login-server
    depends_on:
      - "login-db"
  login-db:
    image: login-db
    volumes:
      - login-data:/var/lib/mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "1"
  order-server:
    image: order-server
    depends_on:
      - "order-db"
  order-db:
    image: order-db
    volumes:
      - order-data:/var/lib/mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "1"
  products-server:
    image: products-server
    depends_on:
      - "products-db"
  products-db:
    image: products-db
    volumes:
      - products-data:/var/lib/mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "1"
  wishlist-server:
    image: wishlist-server
    depends_on:
      - "wishlist-db"
  wishlist-db:
    image: wishlist-db
    volumes:
      - wishlist-data:/var/lib/mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "1"
  web-server:
    image: web-server
    ports:
      - "80:3333"

volumes:
  accounts-data:
  cart-data:
  categories-data:
  items-data:
  login-data:
  order-data:
  products-data:
  wishlist-data:
