version: '2.1'

services:
  config:
    image: config
    healthcheck:
      test: ["CMD", "curl", "http://localhost:8888"]
      interval: 10s
      timeout: 1m
  registration:
    image: registration
    healthcheck:
      test: ["CMD", "curl", "http://localhost:1111"]
      interval: 10s
      timeout: 1m
    depends_on:
      config:
        condition: service_healthy
    ports:
      - "1111:1111"
  gateway:
    image: gateway
    healthcheck:
      test: ["CMD", "curl", "http://localhost:4000"]
      interval: 10s
      timeout: 1m   
    depends_on:
      registration:
        condition: service_healthy
  accounts-server:
    image: accounts-server
    depends_on:
      gateway:
        condition: service_healthy
  cart-server:
    image: cart-server
    depends_on:
      gateway:
        condition: service_healthy
  categories-server:
    image: categories-server
    depends_on:
      gateway:
        condition: service_healthy
  items-server:
    image: items-server
    depends_on:
      gateway:
        condition: service_healthy
  login-server:
    image: login-server
    depends_on:
      gateway:
        condition: service_healthy
  order-server:
    image: order-server
    depends_on:
      gateway:
        condition: service_healthy
  products-server:
    image: products-server
    depends_on:
      gateway:
        condition: service_healthy
  wishlist-server:
    image: wishlist-server
    depends_on:
      gateway:
        condition: service_healthy
  web-server:
    image: web-server
    depends_on:
      gateway:
        condition: service_healthy
    ports:
      - "80:3333"
