version: '3'

services:
  config:
    image: selabaq/config
  registration:
    image: selabaq/registration
    ports:
      - "1111:1111"
  gateway:
    image: selabaq/gateway
  accounts:
    image: selabaq/accounts
    depends_on:
      - "accounts-db"
  accounts-db:
    image: selabaq/accounts-db
    volumes:
      - accounts-data:/var/lib/mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "1"
  cart:
    image: selabaq/cart
    depends_on:
      - "cart-db"
  cart-db:
    image: selabaq/cart-db
    volumes:
      - cart-data:/var/lib/mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "1"
  categories:
    image: selabaq/categories
    depends_on:
      - "categories-db"
  categories-db:
    image: selabaq/categories-db
    volumes:
      - categories-data:/var/lib/mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "1"
  items:
    image: selabaq/items
    depends_on:
      - "items-db"
  items-db:
    image: selabaq/items-db
    volumes:
      - items-data:/var/lib/mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "1"
  login:
    image: selabaq/login
    depends_on:
      - "login-db"
  login-db:
    image: selabaq/login-db
    volumes:
      - login-data:/var/lib/mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "1"
  order:
    image: selabaq/order
    depends_on:
      - "order-db"
  order-db:
    image: selabaq/order-db
    volumes:
      - order-data:/var/lib/mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "1"
  products:
    image: selabaq/products
    depends_on:
      - "products-db"
  products-db:
    image: selabaq/products-db
    volumes:
      - products-data:/var/lib/mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "1"
  wishlist:
    image: selabaq/wishlist
    depends_on:
      - "wishlist-db"
  wishlist-db:
    image: selabaq/wishlist-db
    volumes:
      - wishlist-data:/var/lib/mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "1"
  web:
    image: selabaq/web
    ports:
      - "80:3333"

volumes:
  accounts-data:
  cart-data:
  categories-data:
  items-data:
  login-data:
  order-data:
  products-data:
  wishlist-data:
