---------------------------------------------------------------------------------
---------------  Tables  MICROSERVICE ACCOUNTS  ---------------------------------
---------------------------------------------------------------------------------
USE microservices;

CREATE TABLE `account` (
  `USERNAME` varchar(50) NOT NULL,
  `PASSWORD` varchar(45) DEFAULT NULL,
  `EMAIL` varchar(50) DEFAULT NULL,
  `NAME` varchar(50) DEFAULT NULL,
  `BALANCE` decimal(8,2) DEFAULT '0.00',
  `FLAG_ACTIVE` varchar(1) DEFAULT 'Y' COMMENT 'Y: ACTIVE\nN:NO ACTIVE',
  `INSERT_DATE` date DEFAULT NULL,
  `MODIFY_DATE` date DEFAULT NULL,
  PRIMARY KEY (`USERNAME`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `address` (
  `ID_ADDRESS` int(11) NOT NULL AUTO_INCREMENT,
  `FULL_NAME` varchar(45) DEFAULT NULL,
  `ADDRESS1` varchar(45) DEFAULT NULL,
  `ADDRESS2` varchar(45) DEFAULT NULL,
  `CITY` varchar(45) DEFAULT NULL,
  `PROVINCE` varchar(45) DEFAULT NULL,
  `STATE` varchar(45) DEFAULT NULL,
  `ZIP` varchar(45) DEFAULT NULL,
  `PHONE_NUMEBER` varchar(45) DEFAULT NULL,
  `ID_ACCOUNT` varchar(45) DEFAULT NULL,
  `INSERT_DATE` date DEFAULT NULL,
  `MODIFY_DATE` date DEFAULT NULL,
  `FLAG_ACTIVE` varchar(1) NOT NULL DEFAULT 'Y',
  PRIMARY KEY (`ID_ADDRESS`),
  KEY `ID_ACCOUNT_ADDRESS_idx` (`ID_ACCOUNT`),
  CONSTRAINT `ID_ACCOUNT_ADDRESS` FOREIGN KEY (`ID_ACCOUNT`) REFERENCES `account` (`USERNAME`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;

CREATE TABLE `gift_card` (
  `ID_GIFT` int(11) NOT NULL AUTO_INCREMENT,
  `CODE` varchar(45) DEFAULT NULL,
  `BALANCE_TOT` decimal(10,2) DEFAULT NULL,
  `BALANCE_AVAILABLED` decimal(10,2) DEFAULT NULL,
  `BALANCE_USED` decimal(10,2) DEFAULT NULL,
  `ID_ACCOUNT` varchar(45) DEFAULT NULL,
  `INSERT_DATE` date DEFAULT NULL,
  `MODIFY_DATE` date DEFAULT NULL,
  PRIMARY KEY (`ID_GIFT`),
  KEY `ID_ACCOUNT_GIFT_idx` (`ID_ACCOUNT`),
  CONSTRAINT `ID_ACCOUNT_GIFT` FOREIGN KEY (`ID_ACCOUNT`) REFERENCES `account` (`USERNAME`) ON DELETE NO ACTION ON UPDATE NO ACTION
 ) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;
 
  CREATE TABLE `payment` (
  `ID_PAYMENT` int(11) NOT NULL AUTO_INCREMENT,
  `NAME` varchar(45) DEFAULT NULL,
  `NUMBER` varchar(45) DEFAULT NULL,
  `EXPIRATION_MONTH` varchar(45) DEFAULT NULL,
  `EXPIRATION_YEAR` int(4) DEFAULT NULL,
  `ID_ACCOUNT` varchar(45) DEFAULT NULL,
  `INSERT_DATE` date DEFAULT NULL,
  `MODIFY_DATE` date DEFAULT NULL,
  `FLAG_ACTIVE` varchar(1) NOT NULL,
  PRIMARY KEY (`ID_PAYMENT`),
  KEY `ID_ACCOUNT_idx` (`ID_ACCOUNT`),
  CONSTRAINT `ID_ACCOUNT_PAYMENT` FOREIGN KEY (`ID_ACCOUNT`) REFERENCES `account` (`USERNAME`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;
