# Map the error path to error template (for Thymeleaf)
error:
  path=/error

# Discovery Server Access
eureka:
  client:
    serviceUrl:
      defaultZone: http://user:password@registration:1111/eureka/
      
      #  instance:
      #    preferIpAddress: true
      #    ip-address: localhost

# HTTP Server
server:
  context-path: /cart
  port: ${CART_SERVICE_PORT}   # HTTP (Tomcat) port
  #address: 127.0.0.1
  tomcat:
    max-threads: 500
    
logging:
  level:
    com.netflix.discovery: DEBUG
    com.netflix.discovery.TimedSupervisorTask: "OFF"
